name: Log DTS Team issue type

on:
  issues:
    types: [field_added, field_removed]

jobs:
  log-dts-team:
    if: github.event.issue_field.name == 'DTS Team'
    runs-on: ubuntu-latest
    steps:
      - name: Log DTS Team value
        run: echo '${{ github.event.issue_field_value.option.name }}'
